name: Automatic Sync with Dreamhost

on: [push]
    # branches: [main]
jobs:
  deploy_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: ssh deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: ${{ secrets.SSH_USERNAME }}
          server: ${{ secrets.SSH_HOST }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: './*'
          remote_path: '/home/hhftp2/bykassem.com/'
          args: '-o ConnectTimeout=5'